# Project: Day2_Class_Object
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = TestDate.o
LINKOBJ  = TestDate.o
LIBS     = -L"C:/Users/dac/Downloads/MinGW/lib" -L"C:/Users/dac/Downloads/MinGW/x86_64-w64-mingw32/lib" -static-libstdc++ -static-libgcc
INCS     = -I"C:/Users/dac/Downloads/MinGW/include" -I"C:/Users/dac/Downloads/MinGW/x86_64-w64-mingw32/include" -I"C:/Users/dac/Downloads/MinGW/lib/gcc/x86_64-w64-mingw32/11.2.0/include"
CXXINCS  = -I"C:/Users/dac/Downloads/MinGW/include" -I"C:/Users/dac/Downloads/MinGW/x86_64-w64-mingw32/include" -I"C:/Users/dac/Downloads/MinGW/lib/gcc/x86_64-w64-mingw32/11.2.0/include"
BIN      = Day2_Class_Object.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

TestDate.o: TestDate.cpp
	$(CPP) -c TestDate.cpp -o TestDate.o $(CXXFLAGS)
